version: "3.0"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus-server
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml